SERVICES RUN LOCAL LGTM

diff --git a/nextjs/Dockerfile.tailwind-watcher b/nextjs/Dockerfile.tailwind-watcher
--- a/nextjs/Dockerfile.tailwind-watcher
+++ b/nextjs/Dockerfile.tailwind-watcher
@@ -1,9 +1,14 @@
+
+
 FROM node:21-alpine
 
 WORKDIR /app
 
-COPY . /app
+COPY . .
 
-RUN npm ci
+RUN npm i tailwindcss
 
-CMD npx tailwindcss -i /app/public/static/css/input.css -o /app/public/static/css/styles.css --watch --poll
+# remove /app/public/static/css/styles.css if it exists
+RUN rm -f /app/public/static/css/styles.css
+
+CMD sh -c "npx tailwindcss -i /app/public/static/css/input.css -o /app/public/static/css/styles.css --watch --poll || echo 'Command failed!' && sleep 3600"
